name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Build
        run: go build -v -ldflags "-s -w" -o migrator ./...

      - name: Create Release
        uses: actions/create-release@v1
        with:
          files: |
            ./migrator
          token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
          version: latest
        if: success()
        
      - name: Get Release URL
        id: get_release_url
        run: |
          echo "Release URL: ${{ steps.create_release.outputs.upload_url }}"
        if: steps.create_release.outputs.upload_url
